image: debian/stretch
packages:
  - libssl-dev
  - rustup-toolchain
  - cargo-deb
  - libc-ares-dev
  - pkg-config
  - curl
sources:
  - https://github.com/Luminarys/synapse
repositories:
  rustydebs: https://dl.bintray.com/hummer12007/rustydebs stretch main 379CE192D401AB61
secrets:
  - 758ac31b-78cd-4d55-90ec-9dd834783e4f
tasks:
  - build: |
      cd synapse
      printf 'revision = "%s-%s"\n' "$(date +%s)" "$(git describe --always)" >> Cargo.toml
      cargo build --release --all -v
      cargo deb -v --no-build
  - deploy: |
      export DEBFILE="synapse/target/debian/*.deb"
      export PFILE="$(basename ${DEBFILE})"
      export PN="$(cut -d_ -f1 <<< "${PFILE}")" PV="$(cut -d_ -f2 <<< "${PFILE}" | cut -d- -f1)"
      curl --netrc-file ~/.bintray_netrc -T ${DEBFILE} -XPUT "https://api.bintray.com/content/hummer12007/rustydebs/${PN}/${PV}/pool/${PN::1}/${PN}/${PFILE};deb_distribution=stretch;deb_component=main;deb_architecture=amd64;publish=1;override=1"
