language: rust
cache: cargo
addons:
  apt:
    packages:
      - libssl-dev
matrix:
  fast_finish: true
  include:
    - os: linux
      rust: 1.26.2
      env:
        - TARGET=x86_64-unknown-linux-gnu
    - os: linux
      rust: stable
      env:
        - TARGET=x86_64-unknown-linux-gnu
    - os: osx
      rust: stable
      env: TARGET=x86_64-apple-darwin
install: ci/install.sh
script: ci/script.sh
